# Generated by Django 4.1 on 2022-10-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_Detiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255, null=True)),
                ('fileName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='whole_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=255, null=True)),
                ('data', models.CharField(max_length=255, null=True)),
                ('fileName', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
