# Generated by Django 4.1 on 2022-12-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_whole_data_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('bName', models.CharField(max_length=255, null=True)),
                ('domain', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='orgid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whole_data',
            name='orgid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
