# Generated by Django 4.1 on 2022-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registration_case_detiles_orgid_whole_data_orgid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_project_detils',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setProjectName', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
