# Generated by Django 4.1 on 2022-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_set_folder_detils'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_detiles',
            name='folderName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='folderType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='ocrType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='projectName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='projectType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='targetfiles',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
