# Generated by Django 4.1 on 2022-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_case_detiles_foldername_case_detiles_foldertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='set_folder_detils',
            name='project_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='set_folder_detils',
            name='project_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
