# Generated by Django 4.1 on 2022-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_summary_details_set_folder_detils_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_details',
            name='summary',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
