# Generated by Django 4.1 on 2023-01-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_summary_details_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_table_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
