# Generated by Django 4.1 on 2023-03-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_case_detiles_options_case_detiles_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='packegStatus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
