# Generated by Django 4.1 on 2023-04-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextractJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=255)),
                ('caseid', models.CharField(blank=True, max_length=255)),
                ('orgid', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(max_length=255, null=True)),
            ],
        ),
    ]
