# Generated by Django 4.1 on 2023-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_textractjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfcount_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pages', models.CharField(max_length=255, null=True)),
                ('document', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
