# Generated by Django 4.1 on 2023-06-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pdfcount_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='textractjob',
            name='s3loc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
