# Generated by Django 4.1 on 2023-06-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_textractjob_s3loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcount_details',
            name='document',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdfcount_details',
            name='pages',
            field=models.BigIntegerField(default=0),
        ),
    ]
