# Generated by Django 4.1 on 2023-06-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_pdfcount_details_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textractjob',
            name='csvpath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
