# Generated by Django 4.1 on 2023-07-20 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_textractjob_csvpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.TextField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
                ('empOrgid', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='empOrgid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textractjob',
            name='key_values',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
