# Generated by Django 4.1 on 2023-08-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_empregistration_case_detiles_emporgid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCodes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('location', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='textractjob',
            name='job_id_string',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textractjob',
            name='job_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
