# Generated by Django 4.1 on 2023-10-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_appcodes_textractjob_job_id_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWords',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255, null=True)),
                ('useremail', models.CharField(max_length=255, null=True)),
                ('project', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
                ('empOrgid', models.CharField(max_length=255, null=True)),
                ('folder', models.CharField(max_length=255, null=True)),
                ('searchtitle', models.CharField(max_length=255, null=True)),
                ('searchwords', models.CharField(max_length=255, null=True)),
                ('searchtitlewords', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseCases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('userPersona', models.CharField(max_length=255, null=True)),
                ('process', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('processDiagram', models.CharField(max_length=255, null=True)),
                ('input', models.CharField(max_length=255, null=True)),
                ('sampleInput', models.CharField(max_length=255, null=True)),
                ('output', models.CharField(max_length=255, null=True)),
                ('sampleOutput', models.CharField(max_length=255, null=True)),
                ('videoLink', models.CharField(max_length=255, null=True)),
                ('otherLink', models.CharField(max_length=255, null=True)),
                ('otherCollateral', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='searchtextwords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='summary_details',
            name='googleT5summ',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summary_details',
            name='nltksumm',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textractjob',
            name='search_results',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
