# Generated by Django 4.1 on 2024-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_searchwords_usecases_case_detiles_searchtextwords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_detiles',
            name='CULfileName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='XfileName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
