# Generated by Django 4.1 on 2024-03-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_case_detiles_culfilename_case_detiles_xfilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('filetype', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
