# Generated by Django 4.1 on 2024-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_file_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='farm_details',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('farmname', models.CharField(max_length=255, null=True)),
                ('farmdesc', models.CharField(max_length=255, null=True)),
                ('orgid', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
