# Generated by Django 4.1 on 2024-03-11 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_farm_details_polygon_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_details',
            name='farmdesc',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farm_details',
            name='polygon_coordinates',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, null=True, srid=4326),
        ),
    ]
