# Generated by Django 4.1 on 2024-03-11 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_farm_details_farmdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_details',
            name='polygon_coordinates',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
    ]
