# Generated by Django 4.1 on 2024-03-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_farm_details_polygon_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_details',
            name='polygon_coordinates',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
