# Generated by Django 4.1 on 2024-03-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_farm_details_polygon_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm_details',
            old_name='polygon_coordinates',
            new_name='polygon_coords',
        ),
    ]
