# Generated by Django 4.1 on 2024-03-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_polygon_coordinates_farm_details_polygon_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm_details',
            name='polygon_coords',
        ),
    ]
