# Generated by Django 4.1 on 2024-03-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_farm_details_polygon_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_details',
            name='polygon_coords',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
