# Generated by Django 4.1 on 2024-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_farm_details_polygon_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_detiles',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
