# Generated by Django 4.1 on 2024-03-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_file33loc_all_results_files3loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_detiles',
            name='analogyear',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='farmid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='farmname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='nyers',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='plantdensity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='plantingdate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='plantingmethod',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='selectedholosproduct',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case_detiles',
            name='subblocksize',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
