# Generated by Django 4.1 on 2024-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_registration_city_registration_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_details',
            name='farmarea',
            field=models.BigIntegerField(default=0),
        ),
    ]
